language: python
python:
  - "3.6"      # current default Python on Travis CI
# command to install dependencies
install:
  - pip install --upgrade pip
  - pip install -r requirements.txt
  - pip install pytest
  - pip install pytest-qt
  - pip install coverage
env:
  - MVMGUI_BASEDIR="." MVMGUI="./gui/"
# command to run tests
script:
  - pytest gui/test_basics.py
  - pytest gui/test_run.py
