language: python
python:
  - "3.6"      # current default Python on Travis CI
# command to install dependencies
install:
  - pip install --upgrade pip
  - pip install -r requirements.txt
  - pip install pytest
  - pip install pytest-qt
<<<<<<< HEAD
=======
  - pip install coverage
>>>>>>> 910a9286c4722e53c6cd8f7133a519de7b149098
env:
  - MVMGUI_BASEDIR="." MVMGUI="./gui/"
# command to run tests
script:
  - pytest gui/test_basics.py
  - pytest gui/test_run.py

