language: python
python:
  - "3.6"      # current default Python on Travis CI
# command to install dependencies
install:
  - pip install --upgrade pip
  - pip install -r requirements.txt
  - pip install pytest
  - pip install pytest-qt
env:
  - MVMGUI_BASEDIR="." MVMGUI="./gui/"
# command to run tests
script:
  - python -m pytest gui/test_basics.py --cov=./gui/
  - python -m pytest gui/test_run.py --cov=./gui/

